# run on container-based infrastructure
sudo: false

language: python

addons:
    apt:
        packages:
            - gfortran

env:
  global:
    # wradlib-docs
    - secure: "IGK2D/g89w2J2bJomtPTL2UT6SXlyUV+QfoQZP9MCUDQZI3tRddL2M0YYIO5WegUhPDYuCaQDqZCc03tF+UedZgMhyCAsAQWY8Kgt5cC8EXdj4AEs0L5FHB0yuPkOJhJX2cGezKTMjqFfF7pFQWxYmEK3zFzz/8pVBPa7jPkRn2U0ZlWp3v+vO5WbTYgkFdnYSH6+yTnRbnLHmOTbPg62G75mkDU9/RCCZ4a4oKmz40RKIhroSFQtw8HK4UbwVLQsoE06/iL0Q8dbT0o63W1liXcwUbqoljIBHq2i8RVHB1GrtMFIzY40mgIHVOtlJuw6pg0bNaawTGp3wBIfAdk2sCeKLoX5bPsCewed8Bo+kkYdF4TT8mHJVwPHaKjZ0grhavcboHcgC6+ddUS+4TrS9ZKlFyd87EIhCnqdW4X3n665QM8foP7sB6B+hRYrQFneAoHpuif4ea3/wuk//J8Wd5HlVROkd/1Fxqika0KmDNUH5cH1cvIAa2D37MKCf3nKGe/sCBB/TZBkwcmXl1Q4JA+PWzuC6QSc6qWrKZGiqgvPJKKczto5j1hssUh0tBTO9FM5kue/33TvTq1Hkk1tPfl0e4VFmz3BvlLXKLTDpGF+cPn09irINoZJooA3andBjTynwWDYMbtXDQJ4YwCJXyS3N6yAAyaO8pGV23W3aQ="

matrix:
    include:
    - python: 2.7
      env:
        - PYTHON_VERSION="2.7"
        - COVERALLS="true"
        - DOC_BUILD="true"
    - python: 3.4
      env:
        - PYTHON_VERSION="3.4"
    - python: 3.5
      env:
        - PYTHON_VERSION="3.5"

install: source scripts/install.sh

script:
    - export GDAL_DATA=/home/travis/miniconda2/envs/wradlib/share/gdal
    - xvfb-run coverage run --source wradlib testrunner.py -a

after_success:
    - if [[ "$COVERALLS" == "true" ]]; then coveralls || echo "failed"; fi
    - if [[ "$DOC_BUILD" == "true" ]]; then cd $TRAVIS_BUILD_DIR; scripts/build_docs.sh; fi

deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: wradlib
  password:
    secure: rKiAS61oDiuV2uJvkP2aiXt8hb7boU2p35RWiTLS8b5pSo/BWysThOIf1jmz5GQIpI8uYU+5GajlgtGVq8GmOxprexDgwTfMFF2bsblfUuZwYM3R1tPQuo2poAZ1/m0jPCul60vJJ31B2wEzsneo4tvbM4a7mAoBMMA5auli5o3eVo4P8xnXziMbw/l53bnl+ZYv7qocbt9RIsrgckAdfjLkZy8gAgDxcYXGGybg6K8VN/twSZGMIJfOvjkONhOtRfsiUc8fEu2hF6+HjQfSC07jue4KDPzo3s9hrAS6+fB0v8MV4UsB710VsrqoPuIfhBRo+xj8tW7Y2MPzJq/6kPBrVoQwV7gLTxZ7IWy5y4/Si78rxhXZIKDzo2VS4tNq1wo6xfGXv8pbzal7TOljqzK+ekXJBsXgdVUiGisZJLHTnPr0rkjwY7qzW+mqPqnpLLTCoHYWQE9AlrEQI3jP1FejGB5iyv/A3kDhjaerFkXlu5TXfkE44EpoKp8uURCNdzNiFoACv/68w3BJmWI0IkQR+YWZEBQm0xySMj8zLd5qrhqX/0u2crEC2uUPEQnkwNF1X8fOz3KFozY68KYsvSmIqKPlJFWSpzXYzMzqFnpvSumgb+g8FK/UppmMpukeQXTVSMGHY9k0Hi6I/WoGgmlDMksRB4fMUG0nZXdOqyM=
  on:
    #tags: true
    distributions: sdist #bdist_wheel bdist_wininst -p win
    repo: wradlib/wradlib